# Generated by Django 2.1.5 on 2019-01-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
    ]
